services:
  json-server:
#    build:
#      dockerfile: json-server.Dockerfile
    image: juliakuchle/casa-de-eventos-json-server
    ports:
      - "3000:3000"
  site:
#    build: 
#      dockerfile: site.Dockerfile
    image: juliakuchle/casa-de-eventos-site
    ports:
      - "8080:8080"
    depends_on:
      - json-server